### PR TITLE
chore: add handlers for edge cases

### PR DESCRIPTION
**Pull request by salahawk**
- handle edge cases (appropriate HTTP error codes for different cases)
- return error messages in case of auth-failure

### CODE REVIEW

**Comment by crazydevlegend** [comment]
can you please share the test result on your end?

**Comment by salahawk** [comment]
image
I'm running the proxy on my local machine and configure the proxy on Firefox.

**Comment by salahawk** [comment]
image
It asks me provide username and password when setting the proxy.

**Comment by crazydevlegend** [comment]
can you please browse "google.com"?

**Comment by salahawk** [comment]
image

**Comment by salahawk** [comment]
It works as expected.
And here's the log.
image

**Comment by crazydevlegend** [comment]
that's perfect @salahawk

**Review by crazydevlegend — APPROVED** [review]
good job

**Comment by salahawk** [comment]
Thanks.

**Pull request merged**
